name: "Node"

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
    steps:
      - name: Checkout 🛬
        uses: actions/checkout@v5
      - name: Setup Node ⚙️
        uses: ./.github/actions/setup-node
      - name: Build typescript 📦
        run: npm run build && find dist/main.js
      - name: Lint code 💅
        run: npm run lint
      - name: Run tests ✅
        run: npm run test
